# This file should ensure the existence of records required to run the application in every environment (production,
# development, test). The code here should be idempotent so that it can be executed at any point in every environment.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Example:
#
#   ["Action", "Comedy", "Drama", "Horror"].each do |genre_name|
#     MovieGenre.find_or_create_by!(name: genre_name)
#   end

base_game_rules = Ruleset.create(name: "Base Game")
pok_rules = Ruleset.create(name: "Prophecy of Kings")

Objective.create(title: "Achieve Supremacy", phase: "Status", category: "Public 2", text: "Have your flagship or a war sun in another player's home system or the Mecatol Rex system.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Adapt New Strategies", phase: "Status", category: "Secret", text: "Own 2 faction technologies.\n\n'Valefar Assimilator' technologies do not count towards this objective.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Amass Wealth", phase: "Status", category: "Public 1", text: "Spend 3 influence,3 resources,and 3 trade goods.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Become a Legend", phase: "Status", category: "Public 2", text: "Have units in 4 systems that contain legendary planets,Mecatol Rex,or anomalies.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Become a Martyr", phase: "Action", category: "Secret", text: "Lose control of a planet in a home system.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Become the Gatekeeper", phase: "Status", category: "Secret", text: "Have 1 or more ships in a system that contains an alpha wormhole and 1 or more ships in a system that contains a beta wormhole.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Betray a Friend", phase: "Action", category: "Secret", text: "Win a combat against a player whose promissory note you had in your play area at the start of your tactical action.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Brave the Void", phase: "Action", category: "Secret", text: "Win a combat in an anomaly.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Build Defenses", phase: "Status", category: "Public 1", text: "Have 4 or more structures.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Centralize Galactic Trade", phase: "Status", category: "Public 2", text: "Spend 10 trade goods.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Command an Armada", phase: "Status", category: "Public 2", text: "Have 8 or more non-fighter ships in 1 system.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Conquer the Weak", phase: "Status", category: "Public 2", text: "Control 1 planet that is in another player's home systems.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Construct Massive Cities", phase: "Status", category: "Public 2", text: "Have 7 or more structures.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Control the Borderlands", phase: "Status", category: "Public 2", text: "Have units in 5 systems on the edge of the game board other than your home system.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Control the Region", phase: "Status", category: "Secret", text: "Have 1 or more ships in 6 systems.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Corner the Market", phase: "Status", category: "Public 1", text: "Control 4 planets that each have the same planet trait.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Cut Supply Lines", phase: "Status", category: "Secret", text: "Have 1 or more ships in the same system as another player's space dock.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Darken the Skies", phase: "Action", category: "Secret", text: "Win a combat in another player's home system.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Defy Space and Time", phase: "Status", category: "Secret", text: "Have units in the wormhole nexus.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Demonstrate Your Power", phase: "Action", category: "Secret", text: "Have 3 or more non-fighter ships in the active system at the end of a space combat.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Destroy Heretical Works", phase: "Status", category: "Secret", text: "Purge 2 of your relic fragments of any type.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Destroy their Greatest Ship", phase: "Action", category: "Secret", text: "Destroy another player's war sun or flagship.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Develop Weaponry", phase: "Status", category: "Public 1", text: "Own 2 unit upgrade technologies.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Dictate Policy", phase: "Agenda", category: "Secret", text: "There are 3 or more laws in play.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Discover Lost Outposts", phase: "Status", category: "Public 1", text: "Control 2 planets that have attachments.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Diversify Research", phase: "Status", category: "Public 1", text: "Own 2 technologies in each of 2 colors.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Drive the Debate", phase: "Agenda", category: "Secret", text: "You or a planet you control are elected by an agenda.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Engineer a Marvel", phase: "Status", category: "Public 1", text: "Have your flagship or a war sun on the game board.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Erect a Monument", phase: "Status", category: "Public 1", text: "Spend 8 resources.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Establish Hegemony", phase: "Status", category: "Secret", text: "Control planets that have a combined influence value of at least 12.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Establish a Perimeter", phase: "Status", category: "Secret", text: "Have 4 PDS units on the game board.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Expand Borders", phase: "Status", category: "Public 1", text: "Control 6 planets in non-home systems.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Explore Deep Space", phase: "Status", category: "Public 1", text: "Have units in 3 systems that do not contain planets.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Fight With Precision", phase: "Action", category: "Secret", text: "Use ANTI-FIGHTER BARRAGE to destroy the last of a player's fighters in a system.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Forge an Alliance", phase: "Status", category: "Secret", text: "Control 4 cultural planets.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Form Galactic Brain Trust", phase: "Status", category: "Public 2", text: "Control 5 planets that have technology specialties.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Form a Spy Network", phase: "Status", category: "Secret", text: "Discard 5 action cards.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Foster Cohesion", phase: "Status", category: "Secret", text: "Be neighbors with all other players.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Found Research Outposts", phase: "Status", category: "Public 1", text: "Control 3 planets that have technology specialties.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Found a Golden Age", phase: "Status", category: "Public 2", text: "Spend 16 resources.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Fuel the War Machine", phase: "Status", category: "Secret", text: "Have 3 space docks on the game board.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Galvanize the People", phase: "Status", category: "Public 2", text: "Spend a total of 6 tokens from your tactic and/or strategy pools.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Gather a Mighty Fleet", phase: "Status", category: "Secret", text: "Have 5 dreadnoughts on the game board.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Hoard Raw Materials", phase: "Status", category: "Secret", text: "Control planets that have a combined resource value of at least 12.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Hold Vast Reserves", phase: "Status", category: "Public 2", text: "Spend 6 influence,6 resources,and 6 trade goods.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Improve Infrastructure", phase: "Status", category: "Public 1", text: "Have structures on 3 planets outside of your home system.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Intimidate Council", phase: "Status", category: "Public 1", text: "Have 1 or more ships in 2 systems that are adjacent to Mechatol Rex's system.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Lead from the Front", phase: "Status", category: "Public 1", text: "Spend a total of 3 tokens from your tactic and/or strategy pools.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Learn Secrets of the Cosmos", phase: "Status", category: "Secret", text: "Have 1 or more ships in 3 systems that are each adjacent to an anomaly.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Make History", phase: "Status", category: "Public 1", text: "Have units in 2 systems that contain legendary planets,Mecatol Rex,or anomalies.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Make an Example of their World", phase: "Action", category: "Secret", text: "Use BOMBARDMENT to destroy the last of a player's ground forces on a planet.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Manipulate Galactic Law", phase: "Status", category: "Public 2", text: "Spend 16 influence.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Master the Laws of Physics", phase: "Status", category: "Secret", text: "Own 4 technologies of the same color.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Master the Sciences", phase: "Status", category: "Public 2", text: "Own 2 technologies in each of the 4 colors.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Mechanize The Military", phase: "Status", category: "Secret", text: "Have 1 mech on each of 4 planets.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Mine Rare Metals", phase: "Status", category: "Secret", text: "Control 4 hazardous planets.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Monopolize Production", phase: "Status", category: "Secret", text: "Control 4 industrial planets.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Negotiate Trade Routes", phase: "Status", category: "Public 1", text: "Spend 5 trade goods.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Occupy The Fringe", phase: "Status", category: "Secret", text: "Have 9 or more ground forces on a planet that does not contain 1 of your space docks.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Occupy the Seat of the Empire", phase: "Status", category: "Secret", text: "Control Mechatol Rex and have 3 or more ships in its system.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Patrol Vast Territories", phase: "Status", category: "Public 2", text: "Have units in 5 systems that do not contain planets.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Populate the Outer Rim", phase: "Status", category: "Public 1", text: "Have units in 3 systems on the edge of the game board other than your home system.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Produce En Masse", phase: "Status", category: "Secret", text: "Have units with a combined PRODUCTION value of at least 8 in a single system.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Protect the Border", phase: "Status", category: "Public 2", text: "Have structures on 5 planets outside of your home system.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Prove Endurance", phase: "Action", category: "Secret", text: "Be the last player to pass during a game round.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Push Boundaries", phase: "Status", category: "Public 1", text: "Control more planets than each of 2 of your neighbors.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Raise a Fleet", phase: "Status", category: "Public 1", text: "Have 5 or more non-fighter ships in 1 system.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Reclaim Ancient Monuments", phase: "Status", category: "Public 2", text: "Control 3 planets that have attachments.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Revolutionize Warfare", phase: "Status", category: "Public 2", text: "Own 3 unit upgrade technologies.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Rule Distant Lands", phase: "Status", category: "Public 2", text: "Control 2 planets that are each in or adjacent to a different,other player's home system.", victory_points: 2, ruleset: pok_rules)
Objective.create(title: "Seize An Icon", phase: "Status", category: "Secret", text: "Control a legendary planet.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Spark a Rebellion", phase: "Action", category: "Secret", text: "Win a combat against a player who has the most victory points.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Stake your Claim", phase: "Status", category: "Secret", text: "Control a planet in a system that contains a planet controlled by another player.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Strengthen Bonds", phase: "Status", category: "Secret", text: "Have another player's promissory note in your play area.", victory_points: 1, ruleset: pok_rules)
Objective.create(title: "Subdue the Galaxy", phase: "Status", category: "Public 2", text: "Control 11 planets in non-home systems.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Sway the Council", phase: "Status", category: "Public 1", text: "Spend 8 influence.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Threaten Enemies", phase: "Status", category: "Secret", text: "Have 1 or more ships in a system that is adjacent to another player's home system.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Turn their Fleets to Dust", phase: "Action", category: "Secret", text: "Use SPACE CANNON to destroy the last of a player's ships in a system.", victory_points: 1, ruleset: base_game_rules)
Objective.create(title: "Unify the Colonies", phase: "Status", category: "Public 2", text: "Control 6 planets that each have the same planet trait.", victory_points: 2, ruleset: base_game_rules)
Objective.create(title: "Unveil Flagship", phase: "Action", category: "Secret", text: "Win a space combat in a system that contains your flagship.\n\nYou cannot score this objective if your flagship is destroyed in the combat.", victory_points: 1, ruleset: base_game_rules)

Faction.create(name: "Arborec", short_name: "Arborec", ruleset: base_game_rules)
Faction.create(name: "Argent Flight", short_name: "Argent", ruleset: pok_rules)
Faction.create(name: "Barony of Letnev", short_name: "Letnev", ruleset: base_game_rules)
Faction.create(name: "Clan of Saar", short_name: "Saar", ruleset: base_game_rules)
Faction.create(name: "Embers of Muaat", short_name: "Muaat", ruleset: base_game_rules)
Faction.create(name: "Emirates of Hacan", short_name: "Hacan", ruleset: base_game_rules)
Faction.create(name: "Empyrean", short_name: "Empyrean", ruleset: pok_rules)
Faction.create(name: "Federation of Sol", short_name: "Sol", ruleset: base_game_rules)
Faction.create(name: "Ghosts of Creuss", short_name: "Creuss", ruleset: base_game_rules)
Faction.create(name: "L1Z1X Mindnet", short_name: "L1Z1X", ruleset: base_game_rules)
Faction.create(name: "Mahact Gene-Sorcerers", short_name: "Mahact", ruleset: pok_rules)
Faction.create(name: "Mentak Coalition", short_name: "Mentak", ruleset: base_game_rules)
Faction.create(name: "Naalu Collective", short_name: "Naalu", ruleset: base_game_rules)
Faction.create(name: "Naaz-Rokha Alliance", short_name: "Naaz-Rokha", ruleset: pok_rules)
Faction.create(name: "Nekro Virus", short_name: "Nekro", ruleset: base_game_rules)
Faction.create(name: "Nomad", short_name: "Nomad", ruleset: pok_rules)
Faction.create(name: "Sardakk N'orr", short_name: "Sardakk N'orr", ruleset: base_game_rules)
Faction.create(name: "Titans of Ul", short_name: "Titans", ruleset: pok_rules)
Faction.create(name: "Universities of Jol-Nar", short_name: "Jol-Nar", ruleset: base_game_rules)
Faction.create(name: "Vuil'Raith Cabal", short_name: "Vuil'Raith", ruleset: pok_rules)
Faction.create(name: "Winnu", short_name: "Winnu", ruleset: base_game_rules)
Faction.create(name: "Xxcha Kingdom", short_name: "Xxcha", ruleset: base_game_rules)
Faction.create(name: "Yin Brotherhood", short_name: "Yin", ruleset: base_game_rules)
Faction.create(name: "Yssaril Tribes", short_name: "Yssaril", ruleset: base_game_rules)

ExtraVpCondition.create(title: "Holy Planet of Ixth", victory_points: 1)
ExtraVpCondition.create(title: "Shard of the Throne", victory_points: 1)
ExtraVpCondition.create(title: "Crown of Emphidia", victory_points: 1)
ExtraVpCondition.create(title: "Political Censure", victory_points: 1)
ExtraVpCondition.create(title: "Mutiny (Gain VP)", victory_points: 1)
ExtraVpCondition.create(title: "Mutiny (Lose VP)", victory_points: -1)
ExtraVpCondition.create(title: "Seed of an Empire (Gain VP)", victory_points: 1)
ExtraVpCondition.create(title: "Seed of an Empire (Lose VP)", victory_points: -1)
ExtraVpCondition.create(title: "Imperial Rider", victory_points: 1)
ExtraVpCondition.create(title: "Support for the Throne (Red)", victory_points: 1)
ExtraVpCondition.create(title: "Support for the Throne (Green)", victory_points: 1)
ExtraVpCondition.create(title: "Support for the Throne (Yellow)", victory_points: 1)
ExtraVpCondition.create(title: "Support for the Throne (Black)", victory_points: 1)
ExtraVpCondition.create(title: "Support for the Throne (Orange)", victory_points: 1)
ExtraVpCondition.create(title: "Support for the Throne (Pink)", victory_points: 1)
ExtraVpCondition.create(title: "Support for the Throne (Purple)", victory_points: 1)
ExtraVpCondition.create(title: "Support for the Throne (Blue)", victory_points: 1)
ExtraVpCondition.create(title: "First to Mechatol Rex", victory_points: 1)
